version: "3.8"

services:

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust # Establece el método de autenticación como "trust" para permitir todas las conexiones sin autenticación
      POSTGRES_DB: root
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on:
      - postgres

